### ISSUE TITLE
container timezone not taking local machine timezone

### ISSUE THREAD

**Issue by JourneyOver** [tmknight/docker-autoheal#109]
Pretty much the title, since you're using Alpine as the base for your Dockerfile, you need to include `tzdata` in the `RUN apk add` section. Without this, the container won't recognize the local machine's timezone, even even the user has the `/etc/localtime:/etc/localtime:ro` mount.

**Comment by tmknight** [comment]
I disagree, works fine for me (and many others).    Check your config.

**Comment by JourneyOver** [comment]
Yet I've had multiple containers that are alpine based not take the local machines timezone through either `/etc/localtime:/etc/localtime:ro` mount or TZ env variable unless I install tzdata through the apk add, I've had friends also have the same issue and every time I've ever looked it up every single answer leads to the fact that you need to install tzdata for alpine based docker containers.

Guess I'll just fork this repository and add it myself if you don't plan on it, since it works perfectly after I go in and add tzdata myself to the container.

**Comment by tmknight** [comment]
That is your prerogative - this is free as in beer software and you may fork and mess with it all you want.  I will not be making a change to suit an individual user (who likely needs to adjust their perms)...at any rate have at it, I hope you learn something.
